#!/bin/pwsh


# SPMATHER
# 2026-06-15
# Version 1.0.0

#Converts text files into a CSV containing hashes for every word

# Example loop with plain text files:
# foreach ($file in ((get-childitem ~/Documents -file *.txt).FullName)) {$shortname = $file.split('/')[-1] ;  Convert-TextToHashCSV -FilePath $file -OutFilePath ./$($shortname)_$(get-random)_hashes.csv -ExcludeNumeral}




function Convert-TextToHashCSV {

    param (
        [Parameter(
            Position          = 0,    
            Mandatory         = $True,
            ValueFromPipeLine = $True
        )]
        [string]$FilePath,

        [Parameter(
            Position          = 0,
            Mandatory         = $False
        )]
        [string]$OutFilePath,

        [Parameter(
            Mandatory         = $False
        )]
        [switch]$ExcludeNumeral
    )
    


    $Content      = (Get-Content $FilePath)
    $ContentSplit = $Content.Split(' ','.',',',';',':',"'",'(',')','?','!','[',']',"`’","`‘")
    $ContentSplit = $ContentSplit.Split("`“","`”")


    if ($OutFilePath -eq $Null) {
        $OutFilePath = "$PSScriptRoot/Hashes.txt"
    }

    if ($PSVersionTable.Platform -eq "UNIX") {
        bash -c "touch $OutFilePath"
        bash -c "chmod 777 $OutFilePath"
    }

    if ($ExcludeNumeral) {
        (0..9) | ForEach-Object {
            $ContentWords = $ContentSplit.Replace($_,"")
        }
    }
    elseif (!($ExcludeNumeral)) {
        $ContentWords = $ContentSplit
    }

    $UniqueContentWords = $ContentWords | Sort-Object | Select-Object -Unique

    foreach ($String in $UniqueContentWords) {
        $String = $String.Trim()
        $String + ',' + (Find-Hash $String) | Out-File -FilePath $OutFilePath -Append  # mport find-hash function first
    }

    Rename-Item -Path $OutFilePath -NewName "$OutFilePath.csv"

}

Write-Host "Function loaded.  Please use Get-Help Convert-TextToHashCSV for help" -ForegroundColor Cyan


# fin
